### ISSUE TITLE
Please add MARSCOIN MRS

### ISSUE THREAD

**Issue by deeppurple72** [brainwallet/brainwallet.github.io#43]
I have 3 TX's stuck in blockchain due to insufficient TX fees....

I will donate 1 LTC if you can add support for MARSCOIN MRS ( scrypt )

it is a "litecoin" clone i believe

site + wallet:  marscoin.org

blockchain explorer:  http://explore.marscoin.org

pubkey_address version:   50

i lost alot of MRS coins trying to send from PC to android wallet...
they are stuck in blockchain...

would like to try using brainwallet to resend the stuck TXs using a higher fee!

i have both the RAW TX & JSON-TX data,
but MRS isnt listed in brainwallet

please help!

or if someone could tell me how to MOD the github src
to add MRS, i'd send them 1 LTC ( if the code works properly )

please post your LTC address here
( sorry, I would send BTC, but only have "dust" )

Thanks.

**Comment by brainwallet** [comment]
Added Marscoin (MRS) in 06e7b0fbf817891933bb5185676a52111c88c672
Unfortunately marscoin explorer (and ABE in general) doesn't have pushtx url so I can't send a transaction to the corresponding network.
