### ISSUE TITLE
80 Bytes of embedded data via OP_RETURN.

### ISSUE THREAD

**Issue by WhatTheF** [brainwallet/brainwallet.github.io#50]
You create an additional txout with value 0 and script "OP_RETURN data".

https://blockchain.info/tx/9cb4a5c615124f977c9bc7e3e6f236bc68b7c1ded414d68ae4d3d87e15ca3df6?show_adv=true

**Comment by brainwallet** [comment]
I don't know how it happened. There's no OP_RETURN or "Hello World From D" in the code and the site is HTTPS protected. Users allowed to create arbitrary transactions.
