### ISSUE TITLE
Random private key generation uses low-quality Math.random()

### ISSUE THREAD

**Issue by concernedhacker666** [brainwallet/brainwallet.github.io#51]
In bitcoinjs-min.js, the randomBytes function uses Math.random, which is insecure in browsers like FireFox that seed using the current timestamp. A malicious user could bruteforce many timestamp values and predict private keys.

**Comment by brainwallet** [comment]
Added secure random support in 2c1e11f03bb63030bca85d50af20e3839ea44bfd, added secure-random-1.1.1 in 4481c12d2db13a89629eb09bf51b9b5340efd3aa
