### ISSUE TITLE
"Send Transaction" fails with "Bad Request"

### ISSUE THREAD

**Issue by kostaz** [brainwallet/brainwallet.github.io#55]
"Send Transaction" with the most simple transaction with 0.001 fee fails with "Bad Request".

Tested raw tx is below:

010000000147f5e7d9085fc9cd95f1054bb95ea7ea96b98f2de83e884d5aaee19b6f2cb08b000000008a4730440220450a41cddd580cf257efe0f5527aeb483a75f444f3ff5891260c839a39e2eb9d02207381a26426e7866687658d869dc8854f00d9a6a099c1b3cd57d9d21ec36de7d9014104e2902771ed79bc100e44fe69a5bbacb654d3a33ab42c6597c5aef2c695ebf888f01b4f942b166f26d0b64339ed8cf23aaf4cdebe162c395e7ce20370ada7d7cdffffffff0298280300000000001976a9145101cf3455e7fc4794178b27c0786f4b1d7ae5fa88ac705d1e00000000001976a914c19de64f3cd99907c4bb9b56a4b127910b746cfb88ac00000000

--- Kosta

**Comment by brainwallet** [comment]
#71
