### ISSUE TITLE
Outputs get spent automatically

### ISSUE THREAD

**Issue by bitsapphire** [brainwallet/brainwallet.github.io#64]
Hello,

After generating a 3 out of 2 wallet I am able to store my private/public keys for each of the participants. 
After generating this address I send a small amount of BTC to this address (0.0002). The amount is correctly recorded and confirmed in the blockchain and is listed as an unspent transaction. 

Afterwards I create a new transaction that spends (0.0001 BTC). This transaction is successful. On the third step I sent more funds to the 3-out-of-2 wallet (0.0003). This is where the issue happens: any funds I deposit in this wallet from second transaction on are automatically spent towards various unknown addresses, and there is never any unspent transactions no matter how much I deposit there.

I have tested this with 2 wallets already. Any idea what might be the issue?

**Comment by aynik** [comment]
^ lol
