### ISSUE TITLE
Is possible to make a workable clamcoin paper wallet?

### ISSUE THREAD

**Issue by konysulphrea** [brainwallet/brainwallet.github.io#73]
Greetings author.

I like to find a way to ensure the users can get it right.

The public key part is 137 in Decimal but the private key is in 133 in decimal according to Clamcoin's source code while other follows the +128 shifting, exponent is still same,with no errors. Thank you.

**Comment by brainwallet** [comment]
Done and done in https://github.com/brainwallet/brainwallet.github.io/commit/98fea03ad9c3341a2e59d8172bdfaad12f9704f5.
